
drop database if exists Finalproject;
Create database Finalproject;
Use Finalproject;

-- 👥Customers Table
CREATE TABLE customers (
    customer_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    gender VARCHAR(10),
    city VARCHAR(50),
    join_date DATE
);

-- 📦 Products Table
CREATE TABLE products (
    product_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    category VARCHAR(50),
    price DECIMAL(10,2)
);

-- 🧾 Orders Table
CREATE TABLE orders (
    order_id INT PRIMARY KEY AUTO_INCREMENT,
    customer_id INT,
    product_id INT,
    quantity INT,
    order_date DATE,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- Contents for customers table
Insert into customers (name, gender, city, join_date) VALUES
('Aisha Bello', 'Female', 'Lagos', '2024-06-12'),
('James Okafor', 'Male', 'Abuja', '2024-03-05'),
('Zainab Musa', 'Female', 'Kano', '2023-11-22'),
('Tunde Bakare', 'Male', 'Lagos', '2025-01-10'),
('Lilian Akpan', 'Female', 'Port Harcourt', '2024-07-01'),
('Michael Smith', 'Male', 'Ibadan', '2025-02-14'),
('Kemi Adeoye', 'Female', 'Lagos', '2023-09-23'),
('Chinedu Eze', 'Male', 'Enugu', '2024-12-11'),
('Grace Johnson', 'Female', 'Kaduna', '2024-05-03'),
('Bola Salami', 'Male', 'Lagos', '2024-08-19');

-- Contents for Products table
Insert into products (name, category, price) VALUES
('Smartphone X', 'Electronics', 150000.00),
('Bluetooth Speaker', 'Electronics', 45000.00),
('Washing Machine', 'Home Appliances', 230000.00),
('Office Chair', 'Furniture', 60000.00),
('Microwave Oven', 'Home Appliances', 75000.00),
('Laptop Pro 15', 'Electronics', 320000.00),
('Standing Fan', 'Home Appliances', 30000.00),
('Bookshelf', 'Furniture', 50000.00),
('Air Conditioner', 'Home Appliances', 280000.00),
('Wireless Mouse', 'Electronics', 10000.00);

-- Contents for Orders table
Insert into orders (customer_id, product_id, quantity, order_date) VALUES
(1, 1, 1, '2025-03-01'),
(2, 2, 2, '2025-03-05'),
(1, 5, 1, '2025-04-10'),
(3, 4, 1, '2025-02-18'),
(5, 1, 1, '2025-06-20'),
(6, 3, 1, '2025-01-22'),
(6, 6, 1, '2025-02-05'),
(4, 2, 1, '2025-03-15'),
(8, 9, 1, '2025-02-28'),
(7, 10, 2, '2025-03-11'),
(2, 4, 1, '2025-04-01'),
(9, 3, 1, '2025-04-04'),
(9, 6, 1, '2025-04-25'),
(10, 1, 1, '2025-03-21'),
(3, 7, 1, '2025-01-18'),
(1, 6, 1, '2025-05-10'),
(5, 10, 1, '2025-03-30'),
(4, 8, 1, '2025-04-18'),
(6, 5, 1, '2025-05-25'),
(2, 9, 1, '2025-06-01');


-- All orders with customer name, product name, quantity, and order date.
SELECT 
    c.name AS customer_name,
    p.name AS product_name,
    o.quantity,
    o.order_date
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
INNER JOIN products p ON o.product_id = p.product_id;

-- All customers from Lagos who joined in 2024
Select * from customers where city = 'Lagos' 
AND YEAR (join_date) = 2024;

-- Total revenue generated by each product
SELECT 
    p.name AS product_name,
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
INNER JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_id, p.name;

-- Top 3 customers who spent the most
SELECT 
    c.name AS customer_name,
    SUM(o.quantity * p.price) AS total_spent
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
INNER JOIN products p ON o.product_id = p.product_id
GROUP BY c.customer_id, customer_name
ORDER BY total_spent DESC
LIMIT 3;


-- Products ordered more than twice;
SELECT 
    p.name AS product_name,
    COUNT(o.order_id) AS order_count
FROM orders o
INNER JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_id, product_name
HAVING order_count > 2;


-- Customer Status using a case statement (New or Existing)
SELECT 
    name AS customer_name,
    join_date,
    CASE 
        WHEN YEAR(join_date) = 2025 THEN 'Joined in 2025'
        ELSE 'Existing'
    END AS customer_status
FROM customers;

-- Products that were never purchased
SELECT 
    p.name AS product_name,
    p.product_id
FROM products p
LEFT JOIN orders o ON p.product_id = o.product_id
WHERE o.product_id IS NULL;

-- Customers who never made an order
SELECT 
    c.customer_id,
    c.name AS customer_name
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL;

